spring:
  application:
    name: api-what-time
    #  datasource:
    #    driver-class-name: org.h2.Driver
    #    password: password
    #    url: 'jdbc:h2:mem:whattimedb'
    #    username: sa
    datasource:
      url: jdbc:postgresql://postgres:5432/whattimedb
      username: aja
      password: ajaja
      driver-class-name: org.postgresql.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

  logging:
    level:
      root: DEBUG
